spring:
  profiles:
    active:
      - EN
      - dog
      - prod

alper:
  jdbcurl: someYmlFileUrlforDB

banana:
  username: bananaPropertyDbUser
  password: bananaPropertyPassword
  jdbcurl: bananaPropertyUrl

---

spring:
  profiles:
    - prod

alper:
  jdbcurl: someProdYmlFileUrlforDB